name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Findings Report Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Run Docker Image Scan
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t iso188/pygoat .

    - name: Docker Login
      run: echo ${{ secrets.PWD }} | docker login -u ${{ secrets.USER }} --password-stdin

    - name: Push Docker Image
      run: docker push iso188/pygoat
    
    - name: Enable Docker Scout on Repo
      run: docker scout repo enable --org iso188/pygoat

    - name: Scan Image
      uses: docker/scout-action@v1.0.9
      with:
        dockerhub-user: ${{ secrets.USER }}
        dockerhub-password: ${{ secrets.PWD }}
        image: iso188/pygoat
        command: quickview,cves
        only-severities: critical,high
